// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using timebot.Contexts;

namespace timebot.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200821135042_removingDross")]
    partial class removingDross
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("timebot.Classes.Assets.Asset", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AssetType")
                        .HasColumnName("AssetType")
                        .HasColumnType("text");

                    b.Property<string>("Attack")
                        .HasColumnName("Attack")
                        .HasColumnType("text");

                    b.Property<string>("Cost")
                        .HasColumnName("Cost")
                        .HasColumnType("text");

                    b.Property<string>("Counterattack")
                        .HasColumnName("Counterattack")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("text");

                    b.Property<string>("HP")
                        .HasColumnName("HP")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("text");

                    b.Property<string>("TechLevel")
                        .HasColumnName("TechLevel")
                        .HasColumnType("text");

                    b.Property<string>("Tier")
                        .HasColumnName("Tier")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnName("Type")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("timebot.Classes.BlameCal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("timestamp")
                        .HasColumnName("timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.ToTable("BlameCals");
                });

            modelBuilder.Entity("timebot.Classes.Tags.Tag", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("timebot.Classes.botcommand", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("commandname")
                        .HasColumnName("commandname")
                        .HasColumnType("text");

                    b.Property<decimal>("serverid")
                        .HasColumnName("serverid")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("id");

                    b.ToTable("BotCommands");
                });
#pragma warning restore 612, 618
        }
    }
}
