// Generated by https://quicktype.io

namespace timebot.Classes.Tags
{
    using System.Collections.Generic;
    using System.Globalization;
    using System;
    using Newtonsoft.Json.Converters;
    using Newtonsoft.Json;
    using Npgsql;
    using System.Linq;

    public class Tag
    {
        public string Name { get; set; }
        public string Description { get; set; }

        public static List<Tag> GetTags ()
        {
            string connectionstring = JsonConvert.DeserializeObject<Dictionary<string, string>> (System.IO.File.ReadAllText (Program.secrets_file)) ["connection_string"];

            using (var conn = new NpgsqlConnection (connectionstring))
            {
                List<Tag> rtn = new List<Tag> ();

                conn.Open ();
                // Retrieve all rows
                using (var cmd = new NpgsqlCommand ("SELECT * FROM tags;", conn))
                using (var reader = cmd.ExecuteReader ())

                while (reader.Read ())
                {
                    Tag temp = new Tag ();
                    for (int i = 0; i < reader.GetColumnSchema ().Count (); i++)
                    {
                        Helper.SetPropValue (temp, reader.GetColumnSchema () [i].ColumnName, reader.GetValue (i).ToString ());
                    }
                    rtn.Add (temp);
                }

                return rtn;
            }
        }
    }
}