// Generated by https://quicktype.io

namespace timebot.Classes.Tags
{
    using System.Collections.Generic;
    using System.Linq;
    using timebot.Contexts;

    public class Tag
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public static List<Tag> GetTags()
        {
            using (var context = new Context())
            {
                var tags = context.Tags.ToList();

                return tags;
            }
        }
    }
}