// Generated by https://quicktype.io

namespace timebot.Classes
{
    using System.Collections.Generic;
    using System.Globalization;
    using System;
    using Newtonsoft.Json.Converters;
    using Newtonsoft.Json;

    public partial class Wiki
    {
        [JsonProperty ("batchcomplete")]
        public string Batchcomplete { get; set; }

        [JsonProperty ("query")]
        public Query Query { get; set; }
    }

    public partial class Query
    {
        [JsonProperty ("pages")]
        public Dictionary<string, Page> Pages { get; set; }
    }

    public partial class Page
    {
        [JsonProperty ("pageid")]
        public int ID { get; set; }

        [JsonProperty ("ns")]
        public string ns { get; set; }

        [JsonProperty ("title")]
        public string Title { get; set; }

        [JsonProperty ("extract")]
        public string Extract { get; set; }
    }

    public partial class Wiki
    {
        public static Wiki FromJson (string json) => JsonConvert.DeserializeObject<Wiki> (json, Converter.Settings);
    }

}