// Generated by https://quicktype.io

namespace timebot.Classes.Assets
{
    using System.Collections.Generic;
    using System.Globalization;
    using System;
    using Newtonsoft.Json.Converters;
    using Newtonsoft.Json;
    using Npgsql;
    using System.Linq;

    public class TrackerAsset
    {
        public string Owner { get; set; }
        public string Asset { get; set; }
        public string Stealthed { get; set; }
        public string Stat { get; set; }
        public string HP { get; set; }
        public string MaxHP { get; set; }
        public string CombinedHP { get; set; }
        public string Type { get; set; }
        public string Attack { get; set; }
        public string Counter { get; set; }
        public string Notes { get; set; }
        public string Location { get; set; }
    }

    public class Asset
    {
        public string Name { get; set; }
        public long HP { get; set; }
        public string Attack { get; set; }
        public string Counterattack { get; set; }

        public string Description { get; set; }

        public string Type { get; set; }

        public string Tier { get; set; }

        public string TechLevel { get; set; }

        public string Cost { get; set; }

        public string AssetType { get; set; }

        public static List<Asset> GetAssets ()
        {
            string connectionstring = JsonConvert.DeserializeObject<Dictionary<string, string>> (System.IO.File.ReadAllText (Program.secrets_file)) ["connection_string"];

            using (var conn = new NpgsqlConnection (connectionstring))
            {
                List<Asset> rtn = new List<Asset> ();

                conn.Open ();
                // Retrieve all rows
                using (var cmd = new NpgsqlCommand ("SELECT * FROM assets;", conn))
                using (var reader = cmd.ExecuteReader ())
                

                while (reader.Read ())
                {
                    Asset temp = new Asset ();
                    for (int i = 0; i < reader.GetColumnSchema ().Count (); i++)
                    {
                        Helper.SetPropValue (temp, reader.GetColumnSchema () [i].ColumnName, reader.GetValue (i).ToString ());
                    }
                    rtn.Add (temp);
                }

                return rtn;
            }
        }
    }

}